### ISSUE TITLE
add generator-star-spacing rule

### ISSUE THREAD

**Issue by voodoods** [8select/eslint-config-8select#4]
### What's the issue?
By default ESLint suggests adding spaces between the term `function` and the asterisks `*`, thus making the syntax for a JS generator function invalid.

### Whats a JS generator?
See [generator function concept](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Statements/function*) description on MDN.

JS generators are used i.e. in [Redux Saga ](https://github.com/redux-saga/redux-saga) but can also be used as a stand-alone concept in non-project-related cases.

### ESLint rule declaration
https://eslint.org/docs/rules/generator-star-spacing

**Comment by rschweizer** [comment]
> By default ESLint suggests adding spaces between the term function and the asterisks *, thus making the syntax for a JS generator function invalid.

That is actually not correct for two reasons:
- First, ESLint does not enforce a specific style by default, see [generator-star-spacing - Rules - ESLint](https://eslint.org/docs/rules/generator-star-spacing). However, Standard does, enforcing spaces on both sides of the `*`, as can be seen [here](https://github.com/standard/eslint-config-standard/blob/master/eslintrc.json#L50).
- But secondly, this does not break JavaScript syntax for generators at all, which can be any of the following:
  ```JavaScript
    function* generator () {}
    function *generator () {}
    function * generator () {}
  ```
